# Generated by Django 5.2.6 on 2025-09-06 00:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareas',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tareas',
            name='prioridad',
            field=models.CharField(default='media', max_length=20),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='estado',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
